import CMSNavbar from "../components/CMSNavbar";
import { Provider } from "../utils/Provider";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full bg-amber-50 text-indigo-950 dark:bg-indigo-950 dark:text-amber-50">
        <Provider>
          {" "}
          <CMSNavbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
