// import CMSNavbar from "@/components/CMSNavbar";
// import { Provider } from "@/utils/Provider";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full bg-white1 text-dark1 dark:bg-dark1 dark:text-white1">
        {/* <Provider> */}
        {/* <CMSNavbar /> */}
        {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
